global:
  scrape_interval: 1m

scrape_configs:
  - job_name: 'ldes-client'
    scrape_interval: 5s
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['ldio-workbench']
  - job_name: 'rdf-seeder'
    scrape_interval: 5s
    metrics_path: '/prometheus'
    static_configs:
      - targets: ['rdf-seeder']
