{
 "title": "IPDC",
 "description": "IPDC seed process follow-up",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "auto",
 "panels": [
  {
   "title": "IPDC entries IN",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    { "expr": "ldio_data_in_total", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "IPDC entries OUT",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    { "expr": "ldio_data_out_total", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "IPDC entries stored",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 16 },
   "targets": [
    { "expr": "rdf_seeder_message_count", "legendFormat": "__auto" }
   ]
  }
 ]
}