# build environment
FROM node:22-bullseye-slim AS builder
# fix vulnerabilities
ARG NPM_TAG=10.8.3
RUN npm install -g npm@${NPM_TAG}
# build it
WORKDIR /build
COPY . .
RUN npm ci
RUN npm run build

# run environment
FROM node:22.9.0-bullseye-slim
# fix vulnerabilities
# note: trivy insists this to be on the same RUN line
RUN apt-get -y update && apt-get -y upgrade
RUN apt-get -y install apt-utils wget
# install signal-handler wrapper
RUN apt-get -y install dumb-init
ENTRYPOINT ["/usr/bin/dumb-init", "--"]
# install package manager
RUN npm install -g npm@${NPM_TAG}
# install rdf seeder
WORKDIR /home/node
COPY --chown=node:node --from=builder /build/package*.json seeder/
COPY --chown=node:node --from=builder /build/dist/*.js seeder/
COPY --chown=node:node --from=builder /build/*.html seeder/
RUN cd ./seeder && npm ci --omit=dev
ENV PORT=80
ENV SPARQL_ENDPOINT=
ENV DEFAULT_GRAPH=
ENV NODE_ENV=production
EXPOSE ${PORT}
# run as node
RUN chown node:node -R /home/node/*
WORKDIR /home/node/seeder
USER node
CMD ["sh", "-c", "node ./server.js --host=0.0.0.0 --port=${PORT} --sparql-endpoint=${SPARQL_ENDPOINT} --default-graph=${DEFAULT_GRAPH}"]
